### ISSUE TITLE
Contributing.md

### ISSUE THREAD

**Issue by OlenaBoichenko** [michahl/goodissues#1]
Hello!
I've found your project and it seems very interesting. But I can't find a contributing.md. Can you help me, please? 

![Screenshot_3](https://github.com/user-attachments/assets/97b1b5d4-3346-459e-8400-29a61f04a453)

**Comment by michahl** [comment]
hi!
thanks for letting me know. you can find the contributing.md [here](https://github.com/michahl/goodissues/blob/main/contributing.md)
